# Setup
title: 이설란2
tagline: 웹 프론트엔드 개발자
url: https://seolranlee.github.io
paginate: 1
baseurl: ""
permalink: pretty
locale: ko_KR
description: 웹 프론트엔드 개발자 이설란의 웹 사이트
# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Seolran Lee
  url: https://github.com/seolranlee
  email: leesugar90@gmail.com

defaults:
  - scope:
      path: ""
    values:
      image:
        path: assets/share_thumb_300x300.png
        height: 300
        width: 300

# Custom vars
version: 3.0.0
