name: Release notes

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - webhook

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
